# Tugas 4.1

no. 1

In [129]:
import numpy as np

In [130]:
np_tinggi = np.array([180, 215, 210, 210, 188, 176, 209, 200])
print(type(np_tinggi))

<class 'numpy.ndarray'>


no .2

In [131]:
np_tinggi_meter = np_tinggi / 100
print(np_tinggi_meter)

[1.8  2.15 2.1  2.1  1.88 1.76 2.09 2.  ]


no. 3

In [132]:
np_berat = np.array([88.5, 100, 98, 101, 78.3, 65.3, 109, 110])
bmi = np_berat / np_tinggi ** 2

print(bmi)

[0.00273148 0.00216333 0.00222222 0.00229025 0.00221537 0.00210808
 0.00249536 0.00275   ]


no. 4

In [133]:
bmi_tinggi = bmi[bmi > 23]
print(bmi_tinggi)

[]


no. 5

Soal :np.array([True, 1, 2]) + np.array([3, 4, False])
Manakah pilihan di bawah ini yang memilik hasil sama seperti di atas ?

Jawab :B. np.array([4, 3, 0]) + np.array([0, 2, 2])

no. 6

In [134]:
print(np_berat[7])
print(np_berat[3:8])

110.0
[101.   78.3  65.3 109.  110. ]


no. 7

In [135]:
basket_2d = np.array([[180, 78.4],                
                 [215, 102.7],                 
                 [210, 98.5],                 
                 [188, 75.2]])

print(type(basket_2d))
print(basket_2d)
print(basket_2d.shape)

<class 'numpy.ndarray'>
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
(4, 2)


no. 8

In [136]:
print(basket_2d[:,0])

[180. 215. 210. 188.]


In [137]:
print(basket_2d[2:,1])

[98.5 75.2]


no. 9

In [138]:
np_mat = np.array([[1, 2],                    
                   [3, 4],                    
                   [5, 6]]) 

print(np_mat * 2) 
print(np_mat + np.array([10, 10])) 
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]
[[11 12]
 [13 14]
 [15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [139]:
basket_2d

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [140]:
print(basket_2d[0][1] + 5, basket_2d[1][1] + 5, basket_2d[2][1] + 5, basket_2d[3][1] + 5)

83.4 107.7 103.5 80.2


In [141]:
print(basket_2d[0][0] / 100, basket_2d[1][0] / 100, basket_2d[2][0] / 100, basket_2d[3][0] / 100)

1.8 2.15 2.1 1.88


no. 10

In [142]:
print(np.mean(np_tinggi))

198.5


In [143]:
print(np.median(np_tinggi))

204.5


no. 11

In [144]:
rata_rata = np.mean(basket_2d[:,0])
median = np.median(basket_2d[:,0])
stddev = np.std(basket_2d[:,0])
korelasi = np.corrcoef(basket_2d[:,0])

print('Rata - Rata = ', rata_rata)
print('Med = ', median)
print('Stdev = ', stddev)
print('Korelasi =', korelasi)

Rata - Rata =  198.25
Med =  199.0
Stdev =  14.635146053251399
Korelasi = 1.0


In [145]:
basket_2d

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [146]:
np_tinggi

array([180, 215, 210, 210, 188, 176, 209, 200])

In [147]:
basket_2d[:,0]

array([180., 215., 210., 188.])